GPT:
  API_KEY: ""
  MODEL: "gpt-4-turbo"
  MAX_TOKENS: 300000
  TEMPERATURE: 0.0

LLAMA:
  API_KEY: ""
  MODEL: "llama3.1-405b"
  MAX_TOKENS: 300000
  TEMPERATURE: 0.0

GPT4_AZ:
  API_KEY: ""
  ENDPOINT: ""
  API_VERSION: "2024-05-01-preview"
  MAX_TOKENS: 1000
  MODEL: "gpt-4o"
  TEMPERATURE: 0.0

GEMINI:
  API_KEY: "" # gemini key
  MAX_TOKENS: 30000
  MODEL: "gemini-3-flash-preview"
  TEMPERATURE: 0.0

alibaba:
  API_KEY: "" # use singapore server
  VOICE: "Aiden"
  VOICE_MODEL: "qwen3-tts-flash"
  T2V_MODEL: "wan2.1-t2v-turbo"
  T2I_MODEL: "wan2.2-t2v-plus"
  VIDEO_SIZE: "1280*720"
  IMAGE_SIZE: "1024*1024"

Tavus:
  API_KEY: ""
  REP_ID: "rb91c99ba958"

QWEN:
  local_dir: ""
